services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ../:/app
      - ~/.ssh:/root/.ssh
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
      - "8976:8976"
      - "8787:8787"
      - "4983:4983"
      - "5173:5173"
      - "4000:4000"
